substitutions:
  name: t-higrow-garten-a806a0
  friendly_name: Garten Monitor a806a0
packages:
  ClubMenthol.T-Higrow: github://ClubMenthol/T-Higrow/t-higrow-main.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ZrR98719iXChmfxdShGzTmDJgdXJZUdxnM8jzSjHqMg=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
